name: Appium SpecFlow Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --publish 4723:4723

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug File Structure
        run: ls -R

      - name: Install libssl
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Match project requirement

      - name: Install Dependencies
        run: |
          dotnet restore AppiumSpecFlowProject1.sln

      - name: Run Tests (Only tap.feature)
        run: |
          dotnet build AppiumSpecFlowProject1.sln
          dotnet test --filter "FullyQualifiedName~AppiumSpecFlowProject1.Features.TapFeature"

