name: Appium SpecFlow Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --publish 4723:4723

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug File Structure
        run: ls -R

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install Android SDK and Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Start Android Emulator (Headless Mode)
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          echo "Starting emulator in headless mode"
          nohup $ANDROID_HOME/emulator/emulator -avd testEmulator -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &
          adb wait-for-device
          adb devices

      - name: Verify Appium Server Status
        run: curl http://localhost:4723/status || echo "Appium server is not running"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install Dependencies
        run: dotnet restore AppiumSpecFlowProject1.sln

      - name: Run Tests (Only tap.feature)
        run: |
          dotnet build AppiumSpecFlowProject1.sln
          dotnet test --filter "FullyQualifiedName~AppiumSpecFlowProject1.Features.TapFeature"
