name: Appium SpecFlow Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --publish 4723:4723

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug File Structure
        run: ls -R

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Install Android SDK and Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl
          
          # Install SDK Command-line tools
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools.zip -d latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          # Accept SDK licenses
          yes | sdkmanager --licenses

          # Install necessary SDK packages
          sdkmanager --install "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;default;x86_64"

          # Create and configure AVD
          avdmanager create avd -n testEmulator -k "system-images;android-30;default;x86_64"

      - name: Start Android Emulator (Headless Mode)
        run: |
          $ANDROID_HOME/emulator/emulator -avd testEmulator -no-window -no-audio -no-boot-anim &
          timeout 600 sh -c 'until adb shell getprop sys.boot_completed | grep -m 1 "1"; do sleep 5; done'
          adb devices

      - name: Verify Appium Server Status
        run: curl http://localhost:4723/status || echo "Appium server is not running"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install Dependencies
        run: dotnet restore AppiumSpecFlowProject1.sln

      - name: Run Tests (Only tap.feature)
        run: |
          dotnet build AppiumSpecFlowProject1.sln
          dotnet test --filter "FullyQualifiedName~AppiumSpecFlowProject1.Features.TapFeature"
