name: Appium SpecFlow Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --publish 4723:4723

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium
        run: |
          npm install -g appium
          appium -v

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify Java Installation
        run: java -version

      - name: Set Android Environment Variables
        run: |
          echo "Setting up Android environment variables"
          echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "ANDROID_AVD_HOME=$HOME/.android/avd" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator" >> $GITHUB_ENV

      - name: Install Android SDK and Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Download Android SDK command-line tools
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Add SDK tools to PATH
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> ~/.bashrc
          source ~/.bashrc

          # Accept SDK licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install required Android components
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

      - name: Verify System Image Installation
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep "system-images;android-30;google_apis;x86_64" || echo "System image not found!"

      - name: Create Android Emulator
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n testEmulator -k "system-images;android-30;google_apis;x86_64" --device "pixel_4" --force
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd
          ls -al $ANDROID_AVD_HOME

      - name: Start Android Emulator
        run: |
          export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          nohup $ANDROID_HOME/emulator/emulator -avd testEmulator -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &
          sleep 90
          adb wait-for-device
          adb devices

      - name: Verify Appium Server Status
        run: curl http://localhost:4723/status || echo "Appium server is not running"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install Dependencies
        run: dotnet restore AppiumSpecFlowProject1.sln

      - name: Run Tests (Only tap.feature)
        run: |
          dotnet build AppiumSpecFlowProject1.sln
          dotnet test --filter "FullyQualifiedName~AppiumSpecFlowProject1.Features.TapFeature"
