name: Appium SpecFlow Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --publish 4723:4723

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug File Structure
        run: ls -R

      - name: Install libssl
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'  # Adjust based on your project

      - name: Install Dependencies
        run: |
          dotnet restore AppiumSpecFlowProject1.sln  # Ensure correct path

      - name: Run Tests
        run: |
          dotnet build AppiumSpecFlowProject1.sln  # Ensure correct path
          dotnet test AppiumSpecFlowProject1/AppiumSpecFlowProject1.csproj --filter "TestCategory=Appium"
